# Config format schema number
format_version: 1

###################
## Model options
model_params:
  model_architecture: "rangeret"

  H: 64                     # range image height
  W: 1024                   # range image width

  input_dims: 5             # range image features
  patch_size: 4             # size of patch
  stride: 4                 # stride (1 for full overlapping, patch_size for no overlapping)

  rem_dim: 128              # output feature from REM

  retnet:
    layers: 4               # number of blocks per stage
    hidden_dim: 128         # input dimension
    ffn_size: 256           # feed forward network dimension
    num_head: 4             # number of heads per layer
    double_v_dim: True      # double v dimension wrt hidden_size
  
  decoder_dim: 64              # semantic head hidden dimension

###################
## Dataset options
dataset_params:
  pc_dataset_type: "SemanticKITTI"
  collate_type: "collate_fn_default"
  ignore_label: 0
  data_config: "./config/labels/semantic-kitti.yaml"
  num_classes: 20
  max_points: 150000 # max of any scan in dataset
  sensor:
    name: "HDL64"
    type: "spherical" # projective
    fov_up: 3
    fov_down: -25 
    img_prop:
      width: 1024
      height: 64
    img_means: #range,x,y,z,signal
      - 12.12
      - 10.88
      - 0.23
      - -1.04
      - 0.21
    img_stds: #range,x,y,z,signal
      - 12.32
      - 11.47
      - 6.91
      - 0.86
      - 0.16

###################
## Train params
train_params:
  num_epochs: 128
  learning_rate: 1.0e-2
  optimizer: SGD  # [SGD, Adam]
  batch_size: 1   # batch size (default rangenet 16)
  workers: 12     # number of threads to get data
  #lr_scheduler: CosineAnnealingWarmRestarts  # [StepLR, ReduceLROnPlateau, CosineAnnealingLR, CosineAnnealingWarmRestarts]
  #momentum: 0.9
  #nesterov: True
  #weight_decay: 1.0e-4