# Config format schema number
format_version: 1

###################
## Model options
model_params:
  model_architecture: "rangeret"

  H: 64                     # range image height
  W: 1024                   # range image width

  input_dims: 5             # range image features
  patch_size: [7, 5, 3]             # size of patch
  stride: [4, 3, 2]                 # stride (1 for full overlapping, patch_size for no overlapping)

  rem_dim: 128              # output feature from REM

  embed_dims: [128, 128, 256] # patch features at each stage
  
  heads: [4, 4, 4]          # number of heads at each stage
  mlp_dim: [256, 256, 512]  # mlp dimension at each stage
  blocks: [3, 4, 6]         # number of blocks per stage
  
  decoder_dim: 64           # semantic head hidden dimension

  post:                     # post processing
    KNN:
      use: True
      params:
        knn: 7
        search: 7
        sigma: 1.0 
        cutoff: 1.0

###################
## Dataset options
dataset:
  pc_dataset_type: "SemanticKITTI"
  collate_type: "collate_fn_default"
  ignore_label: 0
  data_config: "./config/labels/semantic-kitti.yaml"
  num_classes: 20
  max_points: 150000 # max of any scan in dataset
  sensor:
    name: "HDL64"
    type: "spherical" # projective
    fov_up: 3
    fov_down: -25 
    img_prop:
      width: 1024
      height: 64
    img_means: #range,x,y,z,signal
      - 12.12
      - 10.88
      - 0.23
      - -1.04
      - 0.21
    img_stds: #range,x,y,z,signal
      - 12.32
      - 11.47
      - 6.91
      - 0.86
      - 0.16

###################
## Train params
train:
  epochs: 64 # default 128
  learning_rate: 1.0e-4 # 1.0e-2 for SGD | 1.0e-4 for AdamW
  optimizer: AdamW  # [SGD, AdamW]
  batch_size: 1   # batch size (default rangenet 16)
  workers: 12     # number of threads to get data
  epsilon_w: 0.001       # class weight w = 1 / (content + epsilon_w)
  
  scheduler:
    OneCycleLR: # Old decay with warmup and cosine annealing 
      max_lr: 0.01 # Equal to optimizer.lr
      total_steps: 1000 # Equal to max_epochs * iterations_per_epoch
      pct_start: 0.02 # The percentage of the cycle (in number of steps) spent increasing the learning rate (warmup).
  
  report_epoch: 1

  #lr_scheduler: CosineAnnealingWarmRestarts  # [StepLR, ReduceLROnPlateau, CosineAnnealingLR, CosineAnnealingWarmRestarts]
  #momentum: 0.9
  #nesterov: True
  #weight_decay: 1.0e-4